### PR TITLE
Re-write the MOI wrapper

### LINKED ISSUE #92: Implement LQOI.get_relative_mip_gap
Ref discussion in https://github.com/JuliaOpt/MathOptInterface.jl/issues/590

### LINKED ISSUE #93: Add documentation for GLPK.Optimizer
Hi all,

There's currently no documentation for GLPK.Optimizer. All we have is a quick mention in the [JuMP Quickstart Docs](http://www.juliaopt.org/JuMP.jl/v0.19.0/quickstart/#Quick-Start-Guide-1).

Any advice on additional options for the optimizer would be appreciated!

Thanks,
Oliver

### LINKED ISSUE #99: Bounds in Binary Variables
The following model
```julia
using JuMP; using GLPK
m = Model()
@variable(m, x, binary=true, lower_bound=0, upper_bound=1)
optimize!(m, with_optimizer(GLPK.Optimizer))
```
results in,
```
ERROR: LoadError: Cannot set bounds because variable is of type: BINARY.
Stacktrace:
 [1] error(::String) at ./error.jl:33
 [2] add_constraints(::GLPK.Optimizer, ::Array{MathOptInterface.SingleVariable,1}, ::Array{MathOptInterface.GreaterThan{Float64},1}) at /.julia/packages/LinQuadOptInterface/ZMx9f/src/constraints/singlevariable.jl:128
 [3] add_constraints(::MathOptInterface.Bridges.LazyBridgeOptimizer{GLPK.Optimizer,MathOptInterface.Utilities.UniversalFallback{MathOptInterface.Bridges.AllBridgedConstraints{Float64}}}, ::Array{MathOptInterface.SingleVariable,1}, ::Array{MathOptInterface.GreaterThan{Float64},1}) at /.julia/packages/MathOptInterface/C3lip/src/Bridges/bridgeoptimizer.jl:342
...
```
Both CBC and Gurobi have no issue with this case.  You might want to support it for consistency.

### LINKED ISSUE #102: Wrong objective bound in MIP with constant term
Consider the model
```julia
using JuMP
m = Model();
@variable(m, x >= 0, Int);
@objective(m, Min, x + 3);
```

The expected result would be "3.0, 3.0", but instead we get "6.0, 3.0"
```julia
using GLPK
JuMP.set_optimizer(m, with_optimizer(GLPK.Optimizer))
JuMP.optimize!(m)
println("GLPK  : ", JuMP.objective_bound(m), " ", JuMP.objective_value(m))
```

To problem seems to come from adding the constant term in the function `LQOI.get_objective_bound(model::Optimizer)`, in `MOI_wrapper.jl` - maybe that was needed some time ago, but not anymore, as can be seen from the results below.
```julia
using LinQuadOptInterface
const LQOI = LinQuadOptInterface;

glpk_model = m.moi_backend.optimizer.model;
LQOI.get_objective_value(glpk_model)
LQOI.get_objective_bound(glpk_model)
LQOI.get_constant_objective(glpk_model)

GLPK.mip_status(glpk_model.inner) == GLPK.OPT
GLPK.mip_obj_val(glpk_model.inner)
glpk_model.objective_bound
```

I tested also Gurobi.jl, which indeed returns "3.0, 3.0"

### PR DESCRIPTION
**Pull request by odow**
Following in the footsteps of https://github.com/JuliaOpt/Gurobi.jl/pull/216

- [x] Requires https://github.com/JuliaOpt/MathOptInterface.jl/pull/767 (remove Manifest.toml once merged and tagged)
- [x] Requires https://github.com/JuliaOpt/MathOptInterface.jl/pull/769

Benchmarks compared to LQOI (part of this improvement comes from disabling GLPK.jl's pre-emptive checks).
```
========== Results ==========

delete_constraint
BenchmarkTools.TrialJudgement: 
  time:   -86.29% => improvement (5.00% tolerance)
  memory: -36.28% => improvement (1.00% tolerance)

add_variable_constraints
BenchmarkTools.TrialJudgement: 
  time:   -43.03% => improvement (5.00% tolerance)
  memory: -56.50% => improvement (1.00% tolerance)

add_variables
BenchmarkTools.TrialJudgement: 
  time:   -43.54% => improvement (5.00% tolerance)
  memory: -36.22% => improvement (1.00% tolerance)

add_constraint
BenchmarkTools.TrialJudgement: 
  time:   -60.16% => improvement (5.00% tolerance)
  memory: -54.59% => improvement (1.00% tolerance)

add_variable
BenchmarkTools.TrialJudgement: 
  time:   -52.77% => improvement (5.00% tolerance)
  memory: -38.20% => improvement (1.00% tolerance)

delete_variable_constraint
BenchmarkTools.TrialJudgement: 
  time:   -81.85% => improvement (5.00% tolerance)
  memory: -96.20% => improvement (1.00% tolerance)

add_variable_constraint
BenchmarkTools.TrialJudgement: 
  time:   -76.90% => improvement (5.00% tolerance)
  memory: -89.06% => improvement (1.00% tolerance)

add_constraints
BenchmarkTools.TrialJudgement: 
  time:   -44.17% => improvement (5.00% tolerance)
  memory: -39.17% => improvement (1.00% tolerance)

delete_variable
BenchmarkTools.TrialJudgement: 
  time:   -36.80% => improvement (5.00% tolerance)
  memory: +2591.58% => regression (1.00% tolerance)
```
Closes #102
Closes #99
Closes #95
Closes #93
Closes #92

### CODE REVIEW

File: src/MOI_wrapper.jl [hunk 1]
```diff
@@ -1,531 +1,1339 @@
...
+MOI.supports(::Optimizer, ::MOI.RawParameter) = true
+
+function MOI.set(model::Optimizer, param::MOI.RawParameter, value)
+    model.params[param.name] = value
+    set_parameter(model, param.name, value)
+    return
+end
+
+function MOI.get(model::Optimizer, param::MOI.RawParameter)
+    error("TODO")
```
Comment (odow) [inline src/MOI_wrapper.jl]: TODO

File: test/MOI_wrapper.jl [hunk 2]
```diff
@@ -1,79 +1,126 @@
...
+    # TODO(odow): check why no certificates are returned.
+    MOIT.lintest(OPTIMIZER, MOIT.TestConfig(infeas_certificates=false))
 end
 
 @testset "Integer Linear tests" begin
-    MOIT.intlineartest(GLPK.Optimizer(), MOIT.TestConfig(), [
-        # int2 is excluded because SOS constraints are not supported.
-        "int2"
+    MOIT.intlineartest(OPTIMIZER, CONFIG, [
+        "int2", "indicator1", "indicator2", "indicator3"
```
Comment (odow) [inline test/MOI_wrapper.jl]: TODO: implement SOS for `int2`

File: test/MOI_wrapper.jl [hunk 3]
```diff
@@ -1,79 +1,137 @@
...
-        # Requires infeasiblity certificate for variable bounds
-        "linear12",
-        # FIXME
-        "partial_start"
-    ])
+@testset "Default Solver"  begin
+        MOIT.contlineartest(OPTIMIZER, MOIT.TestConfig(basis = true), [
+            # This requires an infeasiblity certificate for a variable bound.
+            "linear12",
+            # VariablePrimalStart not supported.
```
Comment (mlubin) [inline test/MOI_wrapper.jl]: Is this a TODO or does GLPK not support providing feasible starting points at all?

File: test/MOI_wrapper.jl [hunk 4]
```diff
@@ -207,20 +246,62 @@ end
...
+    x = MOI.add_variable(model)
+    MOI.add_constraint(model, MOI.SingleVariable(x), MOI.Interval(1.0, -1.0))
+    MOI.optimize!(model)
+    @test MOI.get(model, MOI.TerminationStatus()) == MOI.INVALID_MODEL
+end
+
+@testset "RawParameter" begin
+    model = GLPK.Optimizer(method = GLPK.SIMPLEX)
+    exception = ErrorException("Invalid option: cb_func. Use the MOI attribute `GLPK.CallbackFunction` instead.")
+    @test_throws exception MOI.set(model, MOI.RawParameter(:cb_func), (cb) -> nothing)
```
Comment (mlubin) [inline test/MOI_wrapper.jl]: Do we know that GLPK parameters will always be valid Julia symbol names? This isn't the case for all solvers, so even if it holds for GLPK we should try to be consistent and use strings.

File: src/MOI_wrapper.jl [hunk 5]
```diff
@@ -1,871 +1,1823 @@
...
+@enum(MethodEnum, SIMPLEX, INTERIOR, EXACT)
+
+mutable struct VariableInfo
+    index::MOI.VariableIndex
+    column::Int
+    bound::BoundEnum
+    type::TypeEnum
+    name::String
+    # Storage for constraint names associated with variables because GLPK
+    # can only store names for variables and proper constraints.
```
Comment (mlubin) [inline src/MOI_wrapper.jl]: Now that single-variable constraints are tied to the index of the corresponding variable, I'm wondering if we need to support names for these constraints. You can always lookup the constraint by the variable index or name directly, and no solvers natively support names for bounds.

File: src/MOI_wrapper.jl [hunk 6]
```diff
@@ -1,871 +1,1823 @@
...
 
-"""
-    __internal_callback__(tree::Ptr{Cvoid}, info::Ptr{Cvoid})
-
-Dummy callback function for internal use only. Responsible for updating the
-objective bound.
-"""
+# Dummy callback function for internal use only. Responsible for updating the
+# objective bound and saving the mip gap.
 function __internal_callback__(tree::Ptr{Cvoid}, info::Ptr{Cvoid})
```
Comment (mlubin) [inline src/MOI_wrapper.jl]: Naming: `_internal_callback`.

File: src/MOI_wrapper.jl [hunk 7]
```diff
@@ -1,871 +1,1823 @@
...
 end
 
-"""
-    __internal_callback__(tree::Ptr{Cvoid}, info::Ptr{Cvoid})
-
-Dummy callback function for internal use only. Responsible for updating the
-objective bound.
-"""
+# Dummy callback function for internal use only. Responsible for updating the
+# objective bound and saving the mip gap.
```
Comment (mlubin) [inline src/MOI_wrapper.jl]: and calling the user's callback, it seems?

File: src/MOI_wrapper.jl [hunk 8]
```diff
@@ -1,871 +1,1823 @@
...
+     - `msg_lev::Int`                 Control the log level
+
+    See the GLPK pdf documentation for a full list of parameters.
+    """
+    function Optimizer(; presolve = false, method = SIMPLEX, kwargs...)
+        # GLPK.jl has a lot of pre-emptive checks to catch cases where the C API
+        # might throw an uninformative error. However, in benchmarks, this takes
+        # a non-negligible amount of time (e.g. 20% in add_constraints). Until
+        # someone complains otherwise, we're going to disable these checks
+        GLPK.jl_set_preemptive_check(false)
```
Comment (mlubin) [inline src/MOI_wrapper.jl]: Hmm. It's sketchy to change a global variable so that MOI models run faster. Perhaps add a note in the README that they can choose to speed up GLPK by calling `GLPK.jl_set_preemptive_check(false)`?

File: src/MOI_wrapper.jl [hunk 9]
```diff
@@ -1,871 +1,1823 @@
...
-        return GLPK.FX
-    elseif lower <= -GLPK_INFINITY
-        return upper >= GLPK_INFINITY ? GLPK.FR : GLPK.UP
-    else
-        return upper >= GLPK_INFINITY ? GLPK.LO : GLPK.DB
+function MOI.empty!(model::Optimizer)
+    model.inner = GLPK.Prob()
+    set_parameter(model, :msg_lev, GLPK.MSG_ERR)
+    for (key, value) in model.params
+        set_parameter(model, key, value)
```
Comment (mlubin) [inline src/MOI_wrapper.jl]: Why do you need to set parameters here? `model.params` isn't cleared (and shouldn't be), so the parameters will get picked up on the next solve.

File: src/MOI_wrapper.jl [hunk 10]
```diff
@@ -1,871 +1,1823 @@
...
 
-"""
-    change_row_sense!(model::Optimizer, row, sense)
-
-Convert a linear constraint into another type of linear constraint by changing
-the comparison sense.
+function _rebuild_name_to_variable(model::Optimizer)
+    model.name_to_variable = Dict{String, MOI.VariableIndex}()
+    for (index, info) in model.variable_info
+        if info.name == ""
```
Comment (mlubin) [inline src/MOI_wrapper.jl]: Nit: `if isempty(name)`

File: src/MOI_wrapper.jl [hunk 11]
```diff
@@ -1,871 +1,1823 @@
...
+    return
+end
+
+function MOI.add_constraint(
+    model::Optimizer, f::MOI.SingleVariable, ::MOI.ZeroOne
+)
+    info = _info(model, f.variable)
+    # See https://github.com/JuliaOpt/GLPKMathProgInterface.jl/pull/15
+    # for why this is necesary. GLPK interacts weirdly with binary variables and
+    # bound modification. So lets set binary variables as "Integer" with [0,1]
```
Comment (mlubin) [inline src/MOI_wrapper.jl]: Typo: let's

File: src/MOI_wrapper.jl (hunk 5 above)
Comment (odow) [reply src/MOI_wrapper.jl]: I would be happy to support this. But it means that you can't give a constraint the same name as a variable if you want to look it up.

Comment (mlubin) [reply src/MOI_wrapper.jl]: > But it means that you can't give a constraint the same name as a variable if you want to look it up.

I'm proposing to make setting `ConstraintName` on `SingleVariable` constraint into an error. This wouldn't change lookups otherwise.

To look up the bound on a variable, you first look up the variable. The index of the variable gives you the index of the bound constraint.

Comment (odow) [reply src/MOI_wrapper.jl]: Sounds good.

File: test/MOI_wrapper.jl (hunk 3 above)
Comment (odow) [reply test/MOI_wrapper.jl]: From what I can tell, you have to provide a complete valid basis.

File: src/MOI_wrapper.jl [hunk 12]
```diff
@@ -1,871 +1,1823 @@
...
+    MOI.EqualTo{Float64}, MOI.Interval{Float64}
+}
+
+MOI.supports(::Optimizer, ::MOI.VariableName, ::Type{MOI.VariableIndex}) = true
+MOI.supports(::Optimizer, ::MOI.ConstraintName, ::Type{<:MOI.ConstraintIndex}) = true
+MOI.supports(::Optimizer, ::MOI.ObjectiveFunctionType) = true
+
+MOI.supports(::Optimizer, ::MOI.Name) = true
+MOI.supports(::Optimizer, ::MOI.Silent) = true
+MOI.supports(::Optimizer, ::MOI.ConstraintSet, c) = true
```
[the remark this answers is not in the document]
Comment (blegat) [reply src/MOI_wrapper.jl]: It should be ambiguous with https://github.com/JuliaOpt/MathOptInterface.jl/blob/ef83d2381b2e26a3e6466b8bc34b6687c7c20c61/src/attributes.jl#L122-L131
probably this isn't tested
