### PR TITLE
Call GLPK.factorize when computing infeasibility certificates

### LINKED ISSUE #116: EXACT: no bf solution found (use GLPK.factorize)
The following code, 
```julia
using GLPK
optimizer = GLPK.Optimizer(method=GLPK.EXACT)
using MathOptInterface
const MOI = MathOptInterface
λ = MOI.add_variables(optimizer, 2)
l = MOI.SingleVariable.(λ)
MOI.add_constraint(optimizer, 1.0l[1] + 1.0l[2], MOI.EqualTo(1.0))
MOI.add_constraint(optimizer, -1.0l[1], MOI.EqualTo(-1.0))
MOI.add_constraint(optimizer, l[2], MOI.EqualTo(1.0))
MOI.optimize!(optimizer)
```
throws the error
```
ERROR: LoadError: GLPKError("no bf solution found (use GLPK.factorize)")
Stacktrace:
 [1] _bf_exists at /home/blegat/.julia/packages/GLPK/3DCgA/src/GLPK_checks.jl:271 [inlined]
 [2] macro expansion at /home/blegat/.julia/packages/GLPK/3DCgA/src/GLPK_checks.jl:53 [inlined]
 [3] get_bhead(::Prob, ::Int64) at /home/blegat/.julia/packages/GLPK/3DCgA/src/GLPK.jl:1619
 [4] get_infeasibility_ray(::GLPK.Optimizer, ::Array{Float64,1}) at /home/blegat/.julia/packages/GLPK/3DCgA/src/infeasibility_certificates.jl:49
 [5] optimize!(::GLPK.Optimizer) at /home/blegat/.julia/packages/GLPK/3DCgA/src/MOI_wrapper.jl:1334
```
See https://github.com/JuliaReach/LazySets.jl/pull/1668

### PR DESCRIPTION
**Pull request by odow**
Closes #116

### CODE REVIEW

File: test/MOI_wrapper.jl [hunk 1]
```diff
@@ -383,3 +383,23 @@ end
...
     @test MOI.get(model, MOI.ObjectiveBound()) == 3.0
 end
+
+@testset "Issue #116" begin
+    model = GLPK.Optimizer(method = GLPK.EXACT)
+    x = MOI.add_variables(model, 2)
+    f = MOI.SingleVariable.(x)
+    c1 = MOI.add_constraint(
+        model,
+        MOI.ScalarAffineFunction(
```
Comment (blegat) [inline test/MOI_wrapper.jl]: You can use `1.0f[1] + 1.0f[2]` to build the `MOI.ScalarAffineFunction`

Comment (odow) [reply test/MOI_wrapper.jl]: I had that originally, but I thought it was more explicit to write out directly. I forgot to remove `f` though.
